IF EXISTS(SELECT NAME FROM sys.objects WHERE type = 'P' AND name = 'USP_TDS_GETEXISTINGDEDUCTEESCOUNT')
DROP PROCEDURE USP_TDS_GETEXISTINGDEDUCTEESCOUNT
GO
CREATE PROCEDURE USP_TDS_GETEXISTINGDEDUCTEESCOUNT
 @BRANCHID INT,
 @FORMID INT,
 @QUARTER INT,
 @NAME NVARCHAR(75)
AS
 BEGIN
	DECLARE @SQLQUERY NVARCHAR(MAX)
	CREATE TABLE #CORRDEDSRNO (DEDUCTEESERIALNO INT NULL);
	CREATE TABLE #CORRDEDSRNO1 (DEDUCTEESERIALNO INT NULL,NAME VARCHAR(75) NULL);
	
	IF @FORMID = 1
		BEGIN
			INSERT INTO #CORRDEDSRNO
			SELECT DEDUCTEESERIALNO 
			FROM CORREMPLOYEE WITH(NOLOCK) 
			WHERE BRANCHID = @BRANCHID AND FORMID = @FORMID 
				AND QUARTER = @QUARTER AND  UPDATEINDICATOR = 1 
				AND CORRECTIONSTATUS = 3

			INSERT INTO #CORRDEDSRNO1
			SELECT DEDUCTEESERIALNO,NAME
			FROM CORREMPLOYEE WITH(NOLOCK) 
			WHERE BRANCHID = @BRANCHID AND FORMID = @FORMID 
				AND QUARTER = @QUARTER 
				AND CORRECTIONSTATUS = 1
		END
	ELSE
		BEGIN
			INSERT INTO #CORRDEDSRNO
			SELECT DEDUCTEESERIALNO 
			FROM CORRNONEMPLOYEE WITH(NOLOCK) 
			WHERE BRANCHID = @BRANCHID AND FORMID = @FORMID 
				AND QUARTER = @QUARTER AND  UPDATEINDICATOR = 1 
				AND CORRECTIONSTATUS = 3
			
			INSERT INTO #CORRDEDSRNO1
			SELECT DEDUCTEESERIALNO,NAME 
			FROM CORRNONEMPLOYEE WITH(NOLOCK) 
			WHERE BRANCHID = @BRANCHID AND FORMID = @FORMID 
				AND QUARTER = @QUARTER 
				AND CORRECTIONSTATUS = 1
		END
	
	SELECT DEDUCTEESERIALNO 
	INTO #CORRDEDDETSRNO
    FROM CORRDEDUCTIONDETAIL 
    WHERE BRANCHID = @BRANCHID AND FORMID = @FORMID 
		AND QUARTER = @QUARTER AND CORRECTIONSTATUS = 5
	
	SET @SQLQUERY = N'SELECT COUNT(DEDUCTEESERIALNO) AS RECORDCOUNT 
				   FROM  #CORRDEDSRNO1 
			       WHERE DEDUCTEESERIALNO NOT IN (
												SELECT DEDUCTEESERIALNO 
												FROM #CORRDEDSRNO WITH(NOLOCK)
											  )
				 AND DEDUCTEESERIALNO NOT IN (
												SELECT DEDUCTEESERIALNO 
												FROM #CORRDEDDETSRNO WITH(NOLOCK)
											  )';
	IF(@NAME <> '')
		BEGIN
			SET @SQLQUERY = @SQLQUERY + N' AND NAME LIKE ''' + @NAME + N'%''';
		END

	EXEC SP_EXECUTESQL @SQLQUERY;
	IF OBJECT_ID('tempdb..#CORRDEDSRNO') IS NOT NULL
		DROP TABLE #CORRDEDSRNO
	IF OBJECT_ID('tempdb..#CORRDEDSRNO1') IS NOT NULL
		DROP TABLE #CORRDEDSRNO1
	IF OBJECT_ID('tempdb..#CORRDEDDETSRNO') IS NOT NULL
		DROP TABLE #CORRDEDDETSRNO
 END
 GO

